# Place this content in %USERPROFILE%\.dbt\profiles.yml (Windows)
gidas_explorer:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: localhost
      port: 1433
      database: Envidan_Gidas_SpvPlanDyn_Test
      schema: dbo
      windows_login: true
      encrypt: true
      trust_cert: true